services:
    postgres:
        image: postgres:16
        container_name: nvidia-gpu-detector
        restart: unless-stopped
        environment:
            POSTGRES_USER: kulo
            POSTGRES_PASSWORD: 123456
            POSTGRES_DB: nvidia-gpu-detector
            TZ: Asia/Shanghai
        ports:
            - "5432:5432"
        volumes:
            - ./docker-data/postgres:/var/lib/postgresql/data
